# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: srizd449@gmail.com
author_name: Srizdebnath
contract_name: otc
deployment_language: python
preset_name: starter
project_name: algorand-otc-contracts

